# Generated by Django 4.0.4 on 2022-05-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sitemodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
